languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true

publishDir = "../docs"

theme = "almeida-cv"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

baseURL = "https://cv.laudivan.eti.br/"
title = "Laudivan Almeida"
#googleAnalytics = ""

[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#425526"
colorPageBackground = "#ddd"
colorPrimary = "#81af54"
colorSecondary = "#aaa"
colorIconPrimary = "#fff"
colorIconBackground = "#81af54"
colorRightColumnBackground = "#eaf7de"
colorRightColumnHeadingText = "#81af54"
colorRightColumnBodyText = "#425526"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#81af54"
pages = 2
# Set this param to 'true' to swap the bar positions
swapColumns = false
